const Routes = {
    Authenticated: 'Authenticated',
    NotAuthenticated: 'NotAuthenticated',
    SplashScreen: 'SplashScreen',
    Login: 'Login',
    SignUp: 'SignUp',
    Home: 'Home',
    Auth: 'Auth',
    ForgotPassword: 'ForgotPassword',
    ResetPassword: 'ResetPassword',
    Boarding: 'Boarding',
    BottomTab: 'BottomTab',
    Orders: 'Orders',
    OrderDetails: 'OrderDetails',
    Profile: 'Profile',
    AddCardDetail: 'AddCardDetail',
    Wallet: 'Wallet',
    Payment: 'Payment',
    PickerDetail: 'PickerDetail',
    Booking: 'Booking',
    IsUser: 'IsUser',
    IsDriver: 'IsDriver',
    DriverDemo: 'DriverDemo',
    ConfirmBooking: 'ConfirmBooking',
};
export default Routes;